trigger:
  branches:
    include:
      - develop
      - feature/*
    exclude:
      - master
        
pool:
  vmImage: 'windows-latest'
  
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  
steps:
- task: Docker@2
  inputs:
    command: build
    Dockerfile: .\src\Pipelines.Web\Dockerfile
    arguments: --build-arg PREFIX=$(major).$(minor).$(Build.BuildId) SUFFIX=$(Build.SourceBranchName)
    repository: pipelines

- task: Docker@2
  inputs:
    command: push
    containerRegistry: cstcontainers
    repository: pipelines
    tags: $(major).$(minor).$(Build.BuildId)-$(Build.SourceBranchName)

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish artifacts'
#   inputs:
#     ArtifactName: 'pipeline.artifact'
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'      