trigger:
  branches:
    include:
      - develop
      - feature/*
    exclude:
      - master
        
pool:
  vmImage: 'windows-latest'
  
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  
steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      docker build -t pipelines .\src\Pipelines.Web --build-arg PREFIX=$(major).$(minor).$(Build.BuildId) SUFFIX=$(Build.SourceBranchName)
      docker tag pipelines cstcontainers.azurecr.io/pipelines:latest
      docker push cstcontainers.azurecr.io/pipelines:latest

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish artifacts'
#   inputs:
#     ArtifactName: 'pipeline.artifact'
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'      