trigger:
  branches:
    include:
      - develop
      - features/*
    exclude:
      - master
        
pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  
steps:
- task: DotnetCoreCLI@2
  displayName: 'Create $(solution) publish package'
  inputs:
    command: 'publish'
    projects: '**/Pipelines.Web.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '--configuration $(buildConfiguration) /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)" /p:VersionPrefix=$(major).$(minor).$(Build.BuildId) /p:VersionSuffix=$(Build.SourceBranchName)'
    publishWebProjects: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    ArtifactName: 'pipeline.artifact'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      

      
      
